---
language: python
python: "2.7"

cache: pip

# Use the new container infrastructure
sudo: false

branches:
  only:
  - master
  - test

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # install role
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local
    -e truststore_dir=$TRAVIS_BUILD_DIR/truststore
    -e truststore_owner=travis
    -e truststore_group=travis
    -e truststore_password=password

  # there should be 3 certificates in the trust store now
  - >
    echo password | keytool -list -keystore $TRAVIS_BUILD_DIR/truststore/truststore.jks
    | grep -q "Your keystore contains 3 entries"
    && (echo 'three certs test: pass' && exit 0)
    || (echo 'three certs test: fail' && exit 1)

  # this should do nothing
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local
    -e truststore_dir=$TRAVIS_BUILD_DIR/truststore
    -e truststore_owner=travis
    -e truststore_group=travis
    -e truststore_rebuild=false
    | grep -q 'changed=0.*failed=0'
    && (echo 'rebuild flag test: pass' && exit 0)
    || (echo 'rebuild flag test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
